UKHomeOffice/ide-controller

- packages/react/package.json
- packages/react/src/Components/ChipImage.jsx
- packages/react/src/Components/ImagePanel.jsx
- packages/react/src/Components/InfoTable.jsx
- packages/react/src/Components/InfoTabs.jsx
- packages/react/src/Components/MRZPanel.jsx
- packages/react/src/Components/MRZTable.jsx
- packages/react/src/Components/PageBody.jsx
- packages/react/src/Components/ScanImage.jsx
- packages/react/src/Components/TableRow.jsx
- packages/react/src/Components/Video.jsx
- packages/react/src/__tests__/Video.test.jsx
- packages/react/src/index.jsx
> Fix lint errors

- package.json
- packages/docs/docs/build.md
- packages/docs/docs/doc1.md
- packages/docs/docusaurus.config.js
- packages/docs/sidebars.js
- packages/electron/package.json
> Modify electron build script

- packages/docs/docusaurus.config.js
> COP-2373 deploy docusaurus to github pages

- packages/electron/electron-builder.js
- packages/electron/main.js
- packages/electron/package.json
> COP-2386 Add mac entitlements

- packages/electron/electron-builder.js
- packages/electron/main.js
- packages/electron/package.json
- packages/react/package-lock.json
- packages/react/package.json
Add functionality to run a build command on Windows OS.
\* Required
> COP-2386 Add electron windows build

- packages/electron/main.js
- packages/react/src/Components/LiveImage.jsx
- packages/react/src/Components/Video.jsx
- packages/react/src/__tests__/Video.test.jsx
> COP-2163 Send camera devices list to electron

- packages/react/src/Components/LiveImage.jsx
- packages/react/src/Components/Video.jsx
> COP-2428 Add useEffect with videoRef passed as second arg

- packages/react/src/App.jsx
- packages/react/src/Components/Controller.css
- packages/react/src/Components/Header.jsx
- packages/react/src/Components/PageBody.jsx
Adjust header component to use full width of electron window
\* Required
> COP 1977: Refactor header component

- packages/react/src/Components/Controller.css
- packages/react/src/Components/MatchValue.jsx
Update the style of the match value component. 
\* Required
> COP 1977: Format match value component

- packages/react/public/index.html
- packages/react/src/Components/Controller.css
- packages/react/src/Components/Header.jsx
- packages/react/src/Components/PageBody.jsx
> COP 1977: Format page width

- packages/react/src/Components/Canvas.jsx
- packages/react/src/Components/LiveImage.jsx
> COP-2438 fix memory leak when the cam is left on

- packages/react/src/Components/Canvas.jsx
- packages/react/src/Components/ImagePanel.jsx
- packages/react/src/Components/LiveImage.jsx
> COP-2165 Add restartCam functionality

- .vscode/launch.json
> COP-2445 Add vscode debugger config

- packages/electron/main.js
- packages/electron/menu/common.js
- packages/electron/menu/devMenu.js
- packages/electron/menu/index.js
- packages/electron/menu/prodMenu.js
> COP-2163: Add App Menu

- packages/react/src/Components/Atoms/Button.jsx
- packages/react/src/Components/ImagePanel.jsx
- packages/react/src/Components/PageBody.jsx
> COP-1977 Replace button with Button component

- packages/react/src/Components/Columns/Column.jsx
- packages/react/src/Components/Layout/Column.jsx
> Add Layout Column Component

- packages/react/src/Components/ChipImage.jsx
- packages/react/src/Components/ImagePanel.jsx
- packages/react/src/Components/InfoTable.jsx
- packages/react/src/Components/Layout/Row.jsx
- packages/react/src/Components/Layout/index.js
- packages/react/src/Components/LiveImage.jsx
- packages/react/src/Components/MRZPanel.jsx
- packages/react/src/Components/PhotoHeaders.jsx
- packages/react/src/Components/ScanImage.jsx
Add Row Layout component
All test should pass & IDE-controller layout should match master.
\* Required
> COP-1977 Add Row Layout component

- packages/react/src/Components/Atoms/CanvasImage.jsx
- packages/react/src/helpers/common.js
> Fix CanvasImage error

- packages/idemia-reader-mock/index.js
- packages/idemia-reader-mock/package-lock.json
- packages/idemia-reader-mock/package.json
- packages/idemia-reader-mock/response.json
> COP-2718 Add idemia mock

- packages/react/src/App.jsx
- packages/react/src/Components/Context/index.jsx
- packages/react/src/Components/ImageContext.jsx
- packages/react/src/Components/ImagePanel.jsx
- packages/react/src/Components/LiveImage.jsx
- packages/react/src/Components/StoreContext.jsx
In this PR the Context is updated to be global, easier to find and read.
You should be able to import `{ Provider, Consumer }` just like we used to do without any issues/ errors.
\* Required
> COP-2745 Update React Context API

- packages/react/src/Components/Molecules/DocumentImage.jsx
- packages/react/src/__tests__/Video.test.jsx
Fix invalid prop size error caused by the wrong use of `Column` component
N/A
\* Required
> (4) COP-2773 Fix invalid prop size error

- packages/react/src/Components/Atoms/Button.jsx
- packages/react/src/Components/Atoms/CanvasImage.jsx
- packages/react/src/Components/Atoms/CanvasStrokeRect.jsx
- packages/react/src/Components/Atoms/TableRow.jsx
- packages/react/src/Components/Atoms/Video.jsx
- packages/react/src/Components/Atoms/index.js
- packages/react/src/Components/Molecules/ImagePanel.jsx
- packages/react/src/Components/Molecules/LiveImage.jsx
- packages/react/src/__tests__/Video.test.jsx
- packages/react/src/helpers/camera.js
- packages/react/src/helpers/canvas.js
- packages/react/src/helpers/ipcMainEvents.js
- packages/react/src/index.jsx
In this PR I am visiting each Atom & try to refactor as much as I can.
N/A
\* Required
> (5) COP-2774 Refactor each atom

- packages/react/src/App.jsx
- packages/react/src/config/api-endpoints.js
Move hard coded endpoint to config file
- `npm i && npm run dev`
- No change in IDE Controller behaviour
\* Required
> COP-2846 Move endpoints to config file

- packages/idemia-reader-mock/index.js
- packages/react/src/App.jsx
- packages/react/src/config/api-endpoints.js
> COP-2849 Moack reader status

- packages/electron/main.js
- packages/idemia-reader-mock/index.js
- packages/react/src/App.jsx
- packages/react/src/Components/Atoms/CanvasImage.jsx
- packages/react/src/Components/Atoms/Video.jsx
- packages/react/src/Components/Context/Status.js
- packages/react/src/Components/Molecules/ImageCard.jsx
- packages/react/src/Components/Molecules/LiveImage.jsx
- packages/react/src/Components/Pages/index.jsx
- packages/react/src/Components/Style/global.scss
- packages/react/src/Components/Style/variables.scss
- packages/react/src/config/camera.js
- packages/react/src/helpers/camera.js
- packages/react/src/helpers/canvas.js
When the camera is on and the face is close to the corner of the camera view. The picture is taken. Some parts of the face may be missing e.g chin and forehead.
This PR is to fix this issue.
- `npm i && npm run dev` or
- `npm i && npm run build` then run the application
- Position yourself to the corner of the camera view
- The camera should not take picture
- The live photo view should display red guid around the face
\* Required
> COP-2975 Improve face detection algorithm

- packages/react/src/Components/Atoms/Button.jsx
- packages/react/src/Components/Molecules/DataReadTable.jsx
- packages/react/src/Components/Molecules/ImageComparisonsTable.jsx
- packages/react/src/Components/Molecules/ImagePanel.jsx
- packages/react/src/Components/Molecules/LiveImage.jsx
- packages/react/src/Components/Molecules/MainSection.jsx
- packages/react/src/Components/Molecules/MatchValue.jsx
- packages/react/src/Components/Molecules/PhotoHeaders.jsx
- packages/react/src/Components/Molecules/TableRow.jsx
- packages/react/src/Components/Organisms/Header.jsx
- packages/react/src/Components/Pages/index.jsx
- packages/react/src/Components/Style/global.scss
- packages/react/src/config/camera.js
- packages/react/src/helpers/camera.js
Resize UI to fit surface Go 2 screen
- Run on surface Go 2. 
- Elements should display at a reasonable size. 
\* Required
> COP 1977: Resize components (2)

- packages/react/src/Components/Molecules/MatchValue.jsx
Update average score when no chip image detected
- `npm i && npm dev`
- Scan document that does not have chip
\* Required
> COP Update average score

- packages/electron/main.js
- packages/electron/store.js
- packages/react/src/App.jsx
- packages/react/src/helpers/ipcMainEvents.js
In this PR
- Add `/match` end point data to log
\* Required
> COP-3063 Add to electron store

- packages/react/src/Components/Molecules/DataReadTable.jsx
- packages/react/src/Components/Molecules/ImageComparisonsTable.jsx
- packages/react/src/Components/Molecules/PhotoHeaders.jsx
- packages/react/src/Components/Molecules/TableRow.jsx
Update text to align with prototype iterations. 
- run the command `npm ci && npm run dev`
- if the electron app displays blank, refresh the page with `Cmd + r` or `Ctrl + r`
- All text should align with the prototype, found here [prototype](https://ide.prototype.cop.homeoffice.gov.uk/)
\* Required
> COP 3180: Update text

- packages/react/src/Components/Atoms/Button.jsx
- packages/react/src/Components/Atoms/Image.jsx
- packages/react/src/Components/Atoms/MatchText.jsx
- packages/react/src/Components/Atoms/MatchValue.jsx
- packages/react/src/Components/Atoms/Tag.jsx
- packages/react/src/Components/Molecules/DataReadTable.jsx
- packages/react/src/Components/Molecules/ImageCard.jsx
- packages/react/src/Components/Molecules/ImageComparisonsTable.jsx
- packages/react/src/Components/Molecules/ImagePanel.jsx
- packages/react/src/Components/Molecules/MRZTableHeading.jsx
- packages/react/src/Components/Molecules/MRZTableRow.jsx
- packages/react/src/Components/Molecules/MainSection.jsx
- packages/react/src/Components/Molecules/MatchCard.jsx
- packages/react/src/Components/Organisms/MRZTable.jsx
- packages/react/src/Components/Pages/index.jsx
- packages/react/src/Components/Style/global.scss
- packages/react/src/config/camera.js
> Resize font and fix image border

- packages/react/src/Components/Molecules/MRZTableRow.jsx
- packages/react/src/Components/Molecules/TableRow.jsx
- packages/react/src/Components/Style/global.scss
- packages/react/src/Components/Style/molecules.scss
This PR is to fix [MRZ Table overflow](https://support.cop.homeoffice.gov.uk/browse/COP-3221)
- Scan document
- Check MRZ table
- The MRZ table should match the [design](https://ide.prototype.cop.homeoffice.gov.uk/?nginxId=68c5efd0-6408-48f7-c807-405a98158031)
\* Required
> COP-3221 fix mrz table overflow

- packages/electron/electron-builder.js
> COP-3230 Update win target build to nsis

- packages/electron/main.js
- packages/react/src/App.jsx
- packages/react/src/helpers/ipcMainEvents.js
> 6- Add saveToDesktop helper

- packages/react/src/App.jsx
Branch to fix chip image cacheing bug. 
- pull branch and run command `npm ci && npm run build`
- deploy to development kit
- scan document with chip image
- scan document without chip image 
- Chip image should not display once second document is scanned
\* Required
> 2- COP-3265 Fix cache

- packages/electron/menu/devMenu.js
- packages/idemia-reader-mock/index.js
- packages/react/src/App.jsx
Fix Camera image appearing before the document scans and no Idemia score
- Scan a document while looking at the camera
- After the san finished the score should be updated
\* Required
> COP-3276 Fix Results not updating if live photo take quickly

- packages/react/src/Components/Atoms/Video.jsx
This PR is to force the app to use Logitec C920 webcam otherwise fall back to the system default camera.
- Default camera should be logitect
\* Required
> Default to Logitech C920

- packages/react/src/config/camera.js
> Change camera config

- packages/electron/electron-builder.js
> Add runAfterFinish: false option to windows build

- packages/react/src/App.jsx
- Include UUID (generated with each new scan) in `/match` endpoint
- Scan a document
- Allow the webcam to take a picture
- Check the network requests
- POST request to `/match` endpoint should have `uuid` in request body
\* Required
> COP-3467 Send UUID to /match endpoint

- packages/react/src/helpers/common.js
In this PR SHA-2 function is added from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest)
\* Required
> COP-3495 Add hashing function

- packages/electron/main.js
- packages/electron/store.js
- packages/electron/util/windows.js
In this PR electron try to run `-jar ide-biometrics-0.0.1-exec.jar` command to start biometrics process as child process
- Make sure biometrics is no running in the background
- IDE controller app should start biometrics
\* Required
> COP-3465 Run biometrics process as child process

- packages/electron/main.js
> Pass full javaw path

- packages/react/src/Components/Molecules/MatchCard.jsx
Alter the percentage calculation. 
- Deploy branch to dev device. 
- Run controller, IDEMIA and scanner components. 
- Scan a range of documents. 
- Minimum score should be 21%, Maximum 100%, Pass 50% 
\* Required
> COP 3633: Adjust score calculation

- packages/docs/package-lock.json
- packages/docs/package.json
- packages/electron/package-lock.json
- packages/electron/package.json
- packages/idemia-reader-mock/package-lock.json
- packages/idemia-reader-mock/package.json
- packages/react/package-lock.json
- packages/react/package.json
Update version tag to account for new scoring method. 
- pull branch and run command `npm ci && npm run build`
- navigate to `packages\electron\dist`
- should find the file `IDE Setup 0.0.5.exe`
\* Required
> COP 3633: Update version number

- packages/docs/package-lock.json
- packages/docs/package.json
- packages/electron/main.js
- packages/electron/package-lock.json
- packages/electron/package.json
- packages/idemia-reader-mock/package-lock.json
- packages/idemia-reader-mock/package.json
- packages/react/package-lock.json
- packages/react/package.json
> Update use JAVA_HOME instead of hardcode java version

- packages/electron/main.js
- packages/electron/package-lock.json
- packages/electron/package.json
- packages/electron/store.js
- packages/react/src/App.jsx
- packages/react/src/Components/Molecules/ImagePanel.jsx
- packages/react/src/Components/Molecules/LiveImage.jsx
- packages/react/src/helpers/ipcMainEvents.js
- packages/react/src/helpers/log.js
Improve Logger for the Azure monitor logging branch #148 
\* Required
> 1- COP-3829 update logger

- package-lock.json
- packages/docs/package-lock.json
- packages/docs/package.json
- packages/electron/electron-builder.js
- packages/electron/package-lock.json
- packages/electron/package.json
- packages/electron/yarn.lock
- packages/idemia-reader-mock/package-lock.json
- packages/idemia-reader-mock/package.json
- packages/react/package-lock.json
- packages/react/package.json
Add GUID to application. The build generate new GUID everytime `build` command executed.
\* Required
> COP-3808 Add GUID to application build

- packages/azure-application-insights/index.js
- packages/azure-application-insights/package-lock.json
- packages/azure-application-insights/package.json
- packages/docs/package.json
- packages/electron/build/entitlements.mac.plist
- packages/electron/main.js
- packages/electron/package-lock.json
- packages/electron/package.json
- packages/electron/store.js
- packages/idemia-reader-mock/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/react/src/App.jsx
- packages/react/src/helpers/ipcMainEvents.js
> Add version to log

- .vscode/settings.json
Add our vscode setting to `.vscode/settings.json`
\* Required
> Add vscode eslint setting

- packages/react/src/Components/Atoms/Tag.jsx
- packages/react/src/__tests__/Atoms/Tag.test.jsx
- packages/react/src/__tests__/Atoms/__snapshots__/Tag.test.jsx.snap
> COP-4285 Add Tag Unit & Snapshot tests

- packages/react/src/Components/Atoms/Image.jsx
- packages/react/src/__tests__/Atoms/Image.test.jsx
- packages/react/src/__tests__/Atoms/__snapshots__/Image.test.jsx.snap
Add unit & snapshot test for `Image` component
\* Required
> COP-4284 Add Image Component Test

- packages/azure-application-insights/package-lock.json
- packages/azure-application-insights/package.json
- packages/docs/package-lock.json
- packages/docs/package.json
- packages/electron/package-lock.json
- packages/electron/package.json
- packages/idemia-reader-mock/package-lock.json
- packages/idemia-reader-mock/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/react/src/Components/Atoms/CanvasRect.jsx
https://support.cop.homeoffice.gov.uk/browse/COP-4685
Add visual feedback to the live photo. Green when quality is acceptable, and red when quality is not acceptable.
\* Required
> COP-4685 Add green guid box

- packages/react/src/Components/Molecules/MRZTableRow.jsx
- packages/react/src/Components/Organisms/MRZTable.jsx
- packages/react/src/Components/Style/global.scss
- packages/react/src/helpers/common.js
https://support.cop.homeoffice.gov.uk/browse/COP-3409
\* Required
> COP-3409 highlight MRZ differences

- packages/react/src/helpers/log.js
https://support.cop.homeoffice.gov.uk/browse/COP-4721
\* Required
> COP-4721 Fix: undifined mrzHash

- packages/azure-application-insights/package-lock.json
- packages/azure-application-insights/package.json
- packages/docs/package-lock.json
- packages/docs/package.json
- packages/electron/package-lock.json
- packages/electron/package.json
- packages/idemia-reader-mock/package-lock.json
- packages/idemia-reader-mock/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/react/src/Components/Organisms/MRZTable.jsx
> Fix white screen

- packages/react/src/Components/Atoms/CanvasImage.jsx
- packages/react/src/Components/Atoms/CanvasRect.jsx
- packages/react/src/Components/Atoms/Video.jsx
https://support.cop.homeoffice.gov.uk/browse/COP-3464
\* Required
> COP-3401 Replace null classNames with ''

- packages/react/src/Components/Atoms/StatusBar.jsx
- packages/react/src/Components/Molecules/ImagePanel.jsx
- packages/react/src/Components/Molecules/LiveImage.jsx
- packages/react/src/Components/Style/atoms.scss
- packages/react/src/Components/Style/global.scss
https://support.cop.homeoffice.gov.uk/browse/COP-4581
\* Required
> COP-4581 Add loading animation to status bar

- packages/react/src/helpers/log.js
> COP-5334 Add ExpiryDate to log

- packages/electron/main.js
- packages/electron/menu/index.js
- packages/react/src/Components/Atoms/Video.jsx
- packages/react/src/Components/Molecules/ImagePanel.jsx
- packages/react/src/Components/Molecules/LiveImage.jsx
https://support.cop.homeoffice.gov.uk/browse/COP-3629
This PR is to fix the black live image section bug when after Windows goes to sleep. It also addresses the issue when a Camera is unplugged and when the camera is pluged.
- Leave device until the computer is sleep
- Wake the device and use
- Live image section should show a live stream from the webcam
\* Required
> COP-3629 Update camera imports to be dynamic

- packages/react/src/helpers/log.js
> COP-5379 Skip has MRZ is empty

- packages/react/src/helpers/log.js
https://support.cop.homeoffice.gov.uk/browse/COP-5027
Add 👇 to log
- CD_SAC_STATUS 
- CD_SCBAC_STATUS
- CD_ACTIVE_AUTHENTICATION
@rjweeks would you please be able to verify this change? As I have not tested it. Assuming this data type/ format is identical to the reset this should work.
\* Required
> COP-5027 Add PACE log

- packages/react/src/App.jsx
- packages/react/src/Components/Molecules/ImagePanel.jsx
- packages/react/src/helpers/camera.js
https://support.cop.homeoffice.gov.uk/browse/COP-3464
- [] Send the cropped image to `/match` endpoint
\* Required
> Cop 3464 crop doc image

- packages/react/.eslintrc.js
- packages/react/src/helpers/log.js
https://support.cop.homeoffice.gov.uk/browse/COP-5539
\* Required
> COP-5539 Add docscan hash MRZ

- packages/azure-application-insights/appInsights.js
- packages/azure-application-insights/index.js
- packages/electron/main.js
- packages/electron/store.js
- packages/electron/util/windows.js
- packages/react/src/helpers/globalError.js
- packages/react/src/helpers/ipcMainEvents.js
- packages/react/src/helpers/log.js
> COP-5543 fix log error

- packages/electron/main.js
- packages/electron/util/IDEUpdateExeWatcher.js
- packages/electron/util/helpers.js
https://support.cop.homeoffice.gov.uk/browse/COP-5206
https://github.com/UKHomeOffice/ide-controller/releases/download/1.5.intune-log/ide.Setup.1.3.0.exe
\* Required
> Add .exe fileWatch

- packages/react/src/Components/Molecules/ImagePanel.jsx
> COP-5908 Fix double status bar

- packages/react/src/Components/Molecules/ImagePanel.jsx
- packages/react/src/Components/Molecules/LiveImage.jsx
- packages/react/src/Components/Pages/index.jsx
- packages/react/src/helpers/camera.js
> COP-5907 fix distorted doc scan

- packages/azure-application-insights/package-lock.json
- packages/azure-application-insights/package.json
- packages/docs/package-lock.json
- packages/docs/package.json
- packages/electron/package-lock.json
- packages/electron/package.json
- packages/idemia-reader-mock/package-lock.json
- packages/idemia-reader-mock/package.json
- packages/react/package-lock.json
- packages/react/package.json
> Update version number

- packages/electron/menu/devMenu.js
- packages/idemia-reader-mock/index.js
- packages/react/src/App.jsx
- packages/react/src/Components/Organisms/MRZTable.jsx
> Add doc reader error log

- packages/react/src/App.jsx
- packages/react/src/Components/Molecules/ImagePanel.jsx
> Disable id flip

- packages/azure-application-insights/package-lock.json
- packages/azure-application-insights/package.json
- packages/docs/package-lock.json
- packages/docs/package.json
- packages/electron/package-lock.json
- packages/electron/package.json
- packages/idemia-reader-mock/package-lock.json
- packages/idemia-reader-mock/package.json
- packages/react/package-lock.json
- packages/react/package.json
> update verstion to v2

- packages/react/src/Components/Atoms/Button.jsx
- packages/react/src/Components/Atoms/MatchText.jsx
- packages/react/src/Components/Atoms/MatchValue.jsx
- packages/react/src/Components/Atoms/Tag.jsx
> COP-3420 Add classNames

- packages/electron/util/IDEUpdateExeWatcher.js
> fix string log

- packages/electron/main.js
> prevent multiple instances from running
